name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: lint
        run: make lint

      - name: test
        run: make test
        env:
          PIXELA4GO_E2E_TEST_RUN: ON
          PIXELA4GO_THANKS_CODE: ${{ secrets.PIXELA4GO_THANKS_CODE }}
          PIXELA4GO_USER_NAME: ${{ secrets.PIXELA4GO_USER_NAME }}
          PIXELA4GO_USER_FIRST_TOKEN: ${{ secrets.PIXELA4GO_USER_FIRST_TOKEN }}
          PIXELA4GO_USER_SECOND_TOKEN: ${{ secrets.PIXELA4GO_USER_SECOND_TOKEN }}
